### ISSUE TITLE
Loading error: undefined symbol: LIBXSLT_DEFAULT_PLUGINS_PATH

### ISSUE THREAD

**Issue by MartijnR** [albanm/node-libxslt#18]
Loading the latest node-libxslt module fails.

Reproduce (used node v0.12.7 on Ubuntu 14.04):
1. `npm install libxslt`
2. `node`
`> var libxslt = require('libxslt');`

Error:
```bash
Error: /home/vagrant/node_modules/libxslt/build/Release/node-libxslt.node: undefined symbol: LIBXSLT_DEFAULT_PLUGINS_PATH
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/vagrant/node_modules/libxslt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/vagrant/node_modules/libxslt/index.js:8:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

(this works fine in node-libxslt v0.4.1)

**Comment by MartijnR** [comment]
Is this reproducible for anybody?

**Comment by MartijnR** [comment]
Resolved in 0.5.3. Whoheee! :+1:

**Comment by MartijnR** [comment]
Maybe I cheered too soon. I'll update this.

**Comment by MartijnR** [comment]
I tried dozens of different Ubuntu version/64-32bit/node version combos. In some the issue occurred. In others it didn't. Doesn't seem to relate to any of those 3 parameters.

The only interesting finding is that it seem that when the `npm install libxslt` build outputs the following  log (without failing), the issue **does not** occur.

```bash
==> default: ../deps/libxslt/libxslt/extensions.c: In function ‘xsltExtModuleRegisterDynamic’:
==> default: ../deps/libxslt/libxslt/extensions.c:377:9: warning: implicit declaration of function ‘LIBXSLT_DEFAULT_PLUGINS_PATH’ [-Wimplicit-function-declaration]
==> default:          ext_directory = BAD_CAST LIBXSLT_DEFAULT_PLUGINS_PATH();
==> default:          ^
==> default: In file included from /vagrant/node_modules/libxslt/node_modules/libxmljs-mt/vendor/libxml/include/libxml/tree.h:18:0,
==> default:                  from /vagrant/node_modules/libxslt/node_modules/libxmljs-mt/vendor/libxml/include/libxml/parser.h:16,
==> default:                  from /vagrant/node_modules/libxslt/node_modules/libxmljs-mt/vendor/libxml/include/libxml/globals.h:18,
==> default:                  from /vagrant/node_modules/libxslt/node_modules/libxmljs-mt/vendor/libxml/include/libxml/threads.h:35,
==> default:                  from /vagrant/node_modules/libxslt/node_modules/libxmljs-mt/vendor/libxml/include/libxml/xmlmemory.h:218,
==> default:                  from ../deps/libxslt/libxslt/extensions.c:18:
==> default: /vagrant/node_modules/libxslt/node_modules/libxmljs-mt/vendor/libxml/include/libxml/xmlstring.h:35:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
==> default:  #define BAD_CAST (xmlChar *)
==> default:                   ^
==> default: ../deps/libxslt/libxslt/extensions.c:377:25: note: in expansion of macro ‘BAD_CAST’
==> default:          ext_directory = BAD_CAST LIBXSLT_DEFAULT_PLUGINS_PATH();
==> default:                          ^
==> default: ../deps/libxslt/libxslt/extensions.c: In function ‘xsltRegisterExtModuleElement’:
==> default: ../deps/libxslt/libxslt/extensions.c:1625:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
==> default:      int ret;
==> default:          ^
```

If the above output is missing the issue **does occur**.

It occurs in the default Vagrant environment (Ubuntu 12.04, 64 bit). Do you want a PR that simply adds a test for something like:
 
```js
it('is loadable via require', function(){
  require('libxslt').should.be.type('object');
});
```

**Comment by MartijnR** [comment]
update: 

Even if require('libxslt') doesn't fail. Actually using the module will still show an error:

```bash
dyld: lazy symbol binding failed: Symbol not found: _LIBXSLT_DEFAULT_PLUGINS_PATH
  Referenced from: /Users/martijnvanderijdt/Dropbox/enketo-transformer/node_modules/libxslt/build/Release/node-libxslt.node
  Expected in: dynamic lookup

dyld: Symbol not found: _LIBXSLT_DEFAULT_PLUGINS_PATH
  Referenced from: /Users/martijnvanderijdt/Dropbox/enketo-transformer/node_modules/libxslt/build/Release/node-libxslt.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

**Comment by albanm** [comment]
Ok, sorry for the delay, I will have a look soon. Last items are interesting, I do not reproduce the failure, but I do see the warning. So fixing the latter might do the trick.

Unfortunately I can't take time at work, and my home internet connection is broken right now. So it won't be before a few days.

**Comment by albanm** [comment]
Can you try with the latest release (0.5.4) please ?

**Comment by MartijnR** [comment]
This fixed it! :+1: Fantastic! Thanks a lot. Successfully tested in Ubuntu 14.04 (node 0.10 and 0.12)

(I'm getting a segmentation fault in OS X (node 0.10 and 0.12) but that seems to be entirely different (somewhat known) libxmljs issue.)
