### PR TITLE
Make updates for compatibility with Node 14, 16

### LINKED ISSUE #68: incompatible with node 10
As noted here: gagern/libxmljs#12
I too cant get past node 9 in :
```
%> npm install libxslt 

> libxmljs-mt@0.18.0 install /Users/bosson/Documents/workspace/sites/illuminet-se/node_modules/libxmljs-mt
> node-gyp rebuild

  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc:69:17: error: no member named 'IsDead' in 'v8::V8'
    if (v8::V8::IsDead())
        ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1

```

libxmljs-mt seems stale.

### LINKED ISSUE #72: Make install command giving error in mac
node version - v13.6.0
npm version - 6.13.4

error : 

cd replaceNewNum && npm install && cd ..
up to date in 0.662s
cd local_plugins/com-accenture-cas-plugins-dba && npm install && cd ../..

> libxmljs@0.19.5 install /Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v79-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v79-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v79-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.5 and node@13.6.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v79-darwin-x64.tar.gz 
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2762:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
                                    ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(bool, Boolean)
^~~~~~~~~~~~~~~~
../../nan/nan_converters_43_inl.h:37:29: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::Isolate *' to 'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::Isolate *' to 'v8::Local<v8::Context> &&' for 1st argument
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>'
      against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:4313:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:5688:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1034:53: error: too few arguments to function call, single argument 'context' was not specified
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~~~~~~~~~ ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2750:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1044:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2947:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1818:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1824:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(key, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1830:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(index, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1836:32: error: no matching member function for call to 'Get'
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1842:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(key));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
../../nan/nan.h:1847:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(index));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/shivani.rana/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro
      'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/libxmljs.cc:7:
In file included from ../src/libxmljs.h:7:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:67:18: error: no member named 'MarkIndependent' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    persistent().MarkIndependent();
    ~~~~~~~~~~~~ ^
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro
      'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/libxmljs.cc:8:
../src/xml_document.h:23:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> target);
                           ~~~~^
In file included from ../src/libxmljs.cc:9:
../src/xml_node.h:32:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> target);
                           ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/13.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.6.0/bin/node" "/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs
node-pre-gyp ERR! node -v v13.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/13.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/shivani.rana/cw/App/local_plugins/com-accenture-cas-plugins-dba/node_modules/libxmljs/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.19.5 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.19.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shivani.rana/.npm/_logs/2020-01-18T20_51_54_406Z-debug.log
make: *** [packageInstall] Error 1

### LINKED ISSUE #80: Install error: The lastest libxmljs releases is v0.18.3, why I link to v1.0.0-mt ???????? Are U kidding me ???
```
node-pre-gyp http GET https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-darwin-x64.tar.gz
```

```
https://github.com/gagern/libxmljs/releases/tag/v0.18.3-mt
```

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #80, closes #72, closes #68, addresses short-term issue in #83

Builds with all tests passing on:
- macOS Big Sur version 11.4
- node v16.4.2, 14.17.3, 12.22.3 and 10.24.1
- npm v7.19.1
Also verified all tests pass for https://github.com/enketo/enketo-transformer.

I tried to use https://github.com/renanccastro/libxmljs but compilation failed in my environment. I discovered https://github.com/MrMYHuang/libxmljs which included the changes I needed so I just pointed to that one's [npm release](https://www.npmjs.com/package/node1-libxmljsmt-myh).

### CODE REVIEW

**Comment by albanm** [comment]
I didn't know about the [engines attribute](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) in npm packages, but maybe it would be a good idea to use it to express the node 14+ dependency.

**Comment by lognaturel** [comment]
Thanks for the tip, @albanm, did not know that either! Now that I've thought more about it, I'd rather include Node 12 if possible. I've marked the PR as draft to indicate I'll still be looking into that as well as the CI failure.

**Comment by lognaturel** [comment]
I initially thought this didn't work with node 12.22.3. The build worked fine but when running tests, I got `Error: Module did not self-register: '<path>/node-libxslt/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node'.`

If I `npm rebuild node1-libxmljsmt-myh --build-from-source` first, then tests pass as expected. Same thing with node 10.24.1.  I don't know enough about the tooling to understand what's going on or whether any action needs to be taken. My best guess is that the npm release has macOS binaries built with node 14+ which I pull when building locally with node 12 but then linking fails. Any insights appreciated.

The CI failure was because I had failed to make a Windows-specific change to use the myh fork [here](https://github.com/albanm/node-libxslt/pull/84/commits/200eed11d23079c7418b35a9ffcc53e69688d669#diff-9513a0c08584f4800e1461ca8c3456d1aeb899968ea14b2f6859ea462c37b5bbR13). I've left the CI node version at 12 for now.

**Comment by albanm** [comment]
I don't know why your tests failed in this particular case, but it looks like appveyor build is ok with node 12 so I am not worried.

I will have a closer look soon and certainly merge then release it too.

**Comment by albanm** [comment]
Merged and released.

**Comment by lognaturel** [comment]
Please note that this does not currently work with NPM 7. Filed issue at https://github.com/npm/cli/issues/3556

**Comment by vckeating** [comment]
> I initially thought this didn't work with node 12.22.3. The build worked fine but when running tests, I got `Error: Module did not self-register: '<path>/node-libxslt/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node'.`
> 
> ~If I `npm rebuild node1-libxmljsmt-myh --build-from-source` first, then tests pass as expected. Same thing with node 10.24.1. I don't know enough about the tooling to understand what's going on or whether any action needs to be taken. My best guess is that the npm release has macOS binaries built with node 14+ which I pull when building locally with node 12 but then linking fails. Or maybe it's really just that I had previously built with node 14+ locally and that was being used. Any insights appreciated.~
> 
> From @eyelidlessness:
> 
> > When you tested node versions locally, did you wipe out node_modules and reinstall for each version? Generally anything with native bindings needs to be rebuilt for each version, and that would go for subdeps too
> 
> That makes sense and means that I've verified with node 12.22.3 and 10.24.1 as well. I think this can be released as 0.9.1.
> 
> The CI failure was because I had failed to make a Windows-specific change to use the myh fork [here](https://github.com/albanm/node-libxslt/pull/84/commits/200eed11d23079c7418b35a9ffcc53e69688d669#diff-9513a0c08584f4800e1461ca8c3456d1aeb899968ea14b2f6859ea462c37b5bbR13). I forced push to get that in and I've left the CI node version at 12 for now.

I am able to build the application locally but run into this error when I deploy to my AWS environment which is linux based. `Error: Module did not self-register: 'var/task/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node'.`

I am not sure if this change means I can no longer use this package for a deployment to a linux environment as oppose to windows and wanted to ask. In addtion, I am currently using Node 14 which may be part of the issue since I see here that this updagrade is set for Node 12 and I am guessing creates a compliance issue since this version is pointin at 12 currently. I have been trying to stay away from using Node 12 since this version is already in maintenance mode. https://nodejs.org/en/about/releases/ Is there an intention to continue with upgrading to be node 14 compliant?

**Comment by eyelidlessness** [comment]
@vckeating This change was intended to support Node 14 and 16. I have PRs updating several of our projects to this version, with CI matrix tests of 14 and 16 on Linux (Ubuntu Xenial in some projects due to an oversight on my part, Focal on another).

I have also validated installation with Yarn 1.x on my local Mac while investigating potential solutions to the issues we encountered with NPM 7. I have not tried Yarn in our CI environments. Not sure if either of these may be issues, but for more detail in case this helps track down the problem:

1. Are you using Yarn 2?
2. Are you using Yarn PnP?

And in case the deeply nested quote slipped by, are you upgrading an existing environment, and if so did you try a clean install?

**Comment by vckeating** [comment]
1)
The local version of yarn is v1.22.5 which is what is used to build the yarn.lock file.
Also, the top of the yarn.lock file indicates:

> yarn lockfile v1

and the deployment using yarn v1.22.11

Local is built in a Windows development enviroinment.
During deployment the yarn.lock file us used to build the dependancies needed for the application. The node_modules are ignored by git so that the required details of the dependancy are taken from the yarn lock.. 
The exact command used is:

> yarn install --frozen-lockfile

I have also tried this same libexslt v0.10.0 with Node 12 and it results in the same error when invoking the lambda after AWS deployment.

When building locally I am deleting the node_modules folder and the yarn lock beforeI make the update to the node version and libxslt. Then once they are deleted I run: 

> yarn install

The changes commited are the package.json for the libxslt update and 
Bamboo specs is utilized for the build and deployment of the application.

2)
I do not believe this is using Yarn Pnp, because there are no  .pnp or .cjs files and it is clear that the yarn.lock is designating v1.

**Comment by vckeating** [comment]
Update, the issue with the error was resolved with 2 additional changes in my case. 

In the package.json file I updated the script for "build" to the below:
`"build"" "tsc --build && yarn package-lambda-<LambdaName>`

Without the above in the scrips the node_modules folder was left off the deployment and I recieved a different error when invoking the Lambda. I have seen alternatives where webpack is used but I did not test that.

In addition, there were some additional configuration changes that I had to make to Bamboo Specs v7.
Those settings changes specified the version of node, npm, and yarn by looking at what was indicated for "engines" in the package.json

Hope this is helpful to others who encounter this error.
