### ISSUE TITLE
Project does not build on windows using latest node (8.1.4)

### ISSUE THREAD

**Issue by murrayju** [albanm/node-libxslt#61]
As far as I can tell, this is because of some required changes to libxmljs-mt. I have a pull request open there to get it building again: gagern/libxmljs#10, but I haven't had any luck with using that to fix this project's build (I get some linker errors):

```
node_libxslt.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl libxmljs::WorkerSentinel::~WorkerSentinel(void)" (__imp_??1WorkerSentinel@libxmljs@@UEAA@XZ) [C:\dev\murrayju\libxsltjs\build\node- libxslt.vcxproj]
node_libxslt.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl libxmljs::WorkerSentinel::WorkerSentinel(class libxmljs::WorkerParent &)" (__imp_??0WorkerSentinel@libxmljs@@QEAA@AEAVWorkerParent@1@@Z) [C :\dev\murrayju\libxsltjs\build\node-libxslt.vcxproj]
node_libxslt.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl libxmljs::WorkerParent::~WorkerParent(void)" (__imp_??1WorkerParent@libxmljs@@UEAA@XZ) [C:\dev\murrayju\libxsltjs\build\node-libxsl t.vcxproj]
node_libxslt.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl libxmljs::WorkerParent::WorkerParent(void)" (__imp_??0WorkerParent@libxmljs@@QEAA@XZ) [C:\dev\murrayju\libxsltjs\build\node-libxslt.vcxproj ]
C:\dev\murrayju\libxsltjs\build\Release\node-libxslt.node : fatal error LNK1120: 4 unresolved externals [C:\dev\murrayju\libxsltjs\build\node-libxslt.vcxproj]
```

**Comment by lognaturel** [comment]
Please open a new issue if there are problems with the current versions! CI now builds on Windows so these kinds of problems should be less likely.
