### ISSUE TITLE
node-libxslt fails to build with iojs 3.3.0

### ISSUE THREAD

**Issue by tuananh** [albanm/node-libxslt#24]
node-libxslt fails to build with iojs 3.3.0 with a bunch of error messages like:

    error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value 

It seem sto related to `nan`.

**Comment by albanm** [comment]
Yes, hopefully switching to nan 2 will solve this, cf https://github.com/albanm/node-libxslt/issues/23

Migration is not trivial though, and not in my immediate plans. As usual a pull request would be welcome !

**Comment by benoror** [comment]
@tuananh  Maybe you want to try now  that [Node v4.0.0 (Stable) it's been announced](https://nodejs.org/en/blog/release/v4.0.0/), although probably resulting in the same kind of error.

I personally get the following error:

```
/home/bitnami/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/libxmljs.h:7:0,
                 from ../src/libxmljs.cc:7:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
```

Please refer to the [complete error trace](https://gist.github.com/benoror/3121dac6257564d7d22c)

**Comment by tuananh** [comment]
Thanks. I settled with another lib for now. Will revisit this later



--
Tuan Anh Tran

**Comment by benoror** [comment]
Which one (just curious)?

**Comment by tuananh** [comment]
@benoror i went with another route. I plan to use `xslt` to transform document but changed to jsonpath instead now.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by MartijnR** [comment]
I don't think it's fixed. I added the 4.0, 4.1 and iojs (3.3.1) to Travis using latest master. See results here:

https://travis-ci.org/MartijnR/node-libxslt/jobs/91716497

**Comment by MartijnR** [comment]
corrected link

**Comment by sergeche** [comment]
I was able to successfully compile node-xslt on Travis from master (not from NPM since it contains outdated `libxmljs-mt` dependency; @albanm could you publish new version to NPM, please?).

https://travis-ci.org/sergeche/node-libxslt/builds/92247939

The problem is that new `nan` and Node.js requires more recent version of GCC compiler. So in Travis you should either create custom install script and update GCC or simply switch to Ubuntu Trusty beta image:

```
sudo: required
dist: trusty
```

**Comment by tuananh** [comment]
Awesome ;)



--
Tuan Anh Tranw: https://tuananh.org | e: me@tuananh.org | t: +84 91 223 45 11

**Comment by MartijnR** [comment]
That's fantastic!

**Comment by albanm** [comment]
@sergeche I just published version 0.6.0
